name: issue-comment-workflow
on: issue_comment

jobs:
  pr-comment-job:
    if: github.event.issue.pull_request != null
    runs-on: ubuntu-latest
    steps:
      - name: pr comment
        run: echo ${{ github.event.comment.body }}
  issue-comment-job:
    if: github.event.issue.pull_request == null
    runs-on: ubuntu-latest
    steps:
      - name: issue comment
        run: echo ${{ github.event.comment.body }}